import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hospital-provider-based-department-billing-integrity",
  "engine": "recovery",
  "title": "Hospital Provider-Based Department Billing Integrity",
  "shortTitle": "Hospital Provider-Based Department Billing Integrity",
  "tagline": "Validate provider-based eligibility and recover compliant facility revenue while preventing modifier and notice failures.",
  "industry": "Hospital Outpatient Finance",
  "buyer": "Hospital systems with provider-based departments",
  "uiPort": 4645,
  "apiPort": 5645,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Hospital Provider-Based Department Billing Integrity converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments in one accountable workflow. Validate provider-based eligibility and recover compliant facility revenue while preventing modifier and notice failures.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Hospital Provider-Based Department Billing Integrity evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("department-eligibility-registry","HPB01","Department eligibility registry","Execute department eligibility registry using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed department eligibility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Department eligibility registry Reference","text","HPB01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("ownership-licensure-evidence","HPB02","Ownership licensure evidence","Execute ownership licensure evidence using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed ownership licensure evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Ownership licensure evidence Reference","text","HPB02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("campus-distance-validation","HPB03","Campus-distance validation","Execute campus-distance validation using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed campus-distance validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Campus-distance validation Reference","text","HPB03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("public-awareness-evidence","HPB04","Public awareness evidence","Execute public awareness evidence using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed public awareness evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Public awareness evidence Reference","text","HPB04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("patient-notice-control","HPB05","Patient notice control","Execute patient notice control using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed patient notice control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Patient notice control Reference","text","HPB05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("professional-facility-claim-linking","HPB06","Professional facility claim linking","Execute professional facility claim linking using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed professional facility claim linking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Professional facility claim linking Reference","text","HPB06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("place-of-service-validation","HPB07","Place-of-service validation","Execute place-of-service validation using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed place-of-service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Place-of-service validation Reference","text","HPB07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("po-modifier-control","HPB08","PO modifier control","Execute po modifier control using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed po modifier control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","PO modifier control Reference","text","HPB08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("pn-modifier-control","HPB09","PN modifier control","Execute pn modifier control using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed pn modifier control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","PN modifier control Reference","text","HPB09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("site-neutral-payment-calculation","HPB10","Site-neutral payment calculation","Execute site-neutral payment calculation using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed site-neutral payment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Site-neutral payment calculation Reference","text","HPB10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("split-billing-validation","HPB11","Split-billing validation","Execute split-billing validation using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed split-billing validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Split-billing validation Reference","text","HPB11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("charge-capture-review","HPB12","Charge capture review","Execute charge capture review using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed charge capture review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Charge capture review Reference","text","HPB12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("corrected-claim-workflow","HPB13","Corrected claim workflow","Execute corrected claim workflow using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed corrected claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Corrected claim workflow Reference","text","HPB13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("payment-reconciliation","HPB14","Payment reconciliation","Execute payment reconciliation using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Payment reconciliation Reference","text","HPB14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]}),
feature("department-economics","HPB15","Department economics","Execute department economics using department attestations, ownership, licensure, campus distance, signage, patient notices, professional claims, facility claims, modifiers, and payments.","Produce a governed department economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Department Encounter","text","Facility / Department Encounter · Standard Case"],["caseReference","Department economics Reference","text","HPB15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",535000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",647350],["domainDriver","Department Type","select","On-campus",["On-campus","Off-campus","Remote location"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Department eligibility registry case","Ownership licensure evidence case","Campus-distance validation case","Public awareness evidence case","Patient notice control case"]})
]);
